### ISSUE TITLE
Disable menu items that cannot be used (when not logged in)

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#208]
Gray-out and / or disable pointer

![screen shot 2014-10-13 at 22 48 12](https://cloud.githubusercontent.com/assets/701331/4619900/5a46f214-531a-11e4-9a9d-6933bcc83451.png)

**Comment by patricksavalle** [comment]
I would say: hide when not logged in.

**Comment by jrjackso** [comment]
Is there anything different you need from the pull request I submitted?

**Comment by handijk** [comment]
Looks good to me!
