### ISSUE TITLE
Fine tune TASK TILE1

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#273]
See https://test-www.mobbr.com/#/task/aHR0cDovL3phcGxvZy5ubGw= (invalid URL) and https://test-www.mobbr.com/#/task/aHR0cDovL3phcGxvZy5ubA== (Invalid domain script)

Tile 1 should at least show the error message in the https://test-api.mobbr.com/api_v1/uris/info method

Also if one of these is missing in the page metadata (see return of /api_v1/uris/info method):
- title
- description
- tags
- language

...show this text:
------------------------------------

    One of these properties is missing in your HTML page:
    
    - The HTML <title> element.
    - A <metadata name="description"/> element.
    - A <metadata name="canonical"/> element.
    - A <metadata name="original-source"/> element(s).
    - A <metalink rel="copyright"/> element, defining sharing and derivation rights
    - A correct set of OG-properties, as specified by Facebook.

    Go here (https://github.com/mobbr/mobbr-api-v1/tree/master/specifications ) for instructions

**Comment by handijk** [comment]
facebook and original source are not to be found in the metadata json

**Comment by patricksavalle** [comment]
Don't understand :) It now shows the error test inside the numbered tile, instead of area below?
