### ISSUE TITLE
Regex used for URL normalisation by MOBBR.JS contains error

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#282]
We have a problem with a (misconfigured) QA installation. While it is an error in their configuration, it would have worked if the URL normalisation in our script worked correctly.

This URL:
    http://alterrechner.cwsurf.de//index.php/1/wie-wie-genau

should be normalised to:
    http://alterrechner.cwsurf.de/index.php/1/wie-wie-genau

...before showing the button. This doesn't happen. So this HTML:

    <script type="text/javascript">mobbr.buttonSlim("http://alterrechner.cwsurf.de//index.php/1/wie-wie-genau", "EUR");</script>

Should show exactly the same button as:

    <script type="text/javascript">mobbr.buttonSlim("http://alterrechner.cwsurf.de/index.php/1/wie-wie-genau", "EUR");</script>

Currently we use this code:

    return c || (c = window.location.toString()), c = c.replace(/([^:])(\/\/+)/g, "$1/").replace(/[#\?\/]+$/, ""), a || (a = c), b(a) || a.url || (a.url = c), a

As I read this, the URL is normalised only if we read it from the DOM, not if is was passed as an argument. The URL should ALWAYS be normalised, regardless of source.

**Comment by patricksavalle** [comment]
BTW, I had to format the javascript because there was a minified version in the repo. Our server is using gzip/compression, we don't need minification. I committed a formatted version :)

**Comment by patricksavalle** [comment]
@handijk Think I solved it. Please verify.

**Comment by rolafson** [comment]
@patricksavalle - Has your issue been confirmed resolved? Just saw it on MOBBR and had a look. Due to your reformatting it is difficult to see your actual change in your check-in. Could you post the change here?

**Comment by patricksavalle** [comment]
Hi @rolafson we recovered the original repo (used to be at bitbucket) and it is here: https://github.com/mobbr/mobbr-button

It is solved. The fix is here: https://github.com/mobbr/mobbr-button/blob/master/src/mobbr-button.js#L136

**Comment by patricksavalle** [comment]
@rolafson You got rewarded :)

https://mobbr.com/#/payment/123fedc5a1af03f37d5c3e466b51d668/

It appears our algorithm is somewhat generous towards commenting. We changed that, but the reward is yours :P

**Comment by rolafson** [comment]
@patricksavalle - Indeed, I am a hack from way back. Read an article that mentioned MOBBR. Was fascinated by your take on crowd* so I checked out your site. This issue was on your home page. Figured I'd check it out :-). Thanks for the reward - count me in!
