### ISSUE TITLE
On TASK page add 'static button embeds' en 'pay BTC' button

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#285]
Add to the ' For developers: embed the Mobbr button' section on the /#/task page: show the embed/HTML code for 
- static Mobbr button (an image that redirects to the Mobbr page) 

    `<a href="https://mobbr.com/#/task"><img src="https://api.mobbr.com/images/buttons/mobbr32.png"></a>`
- the bitcoin address

    `<a href="bitcoin:[address]">[address]</a>`

The bitcoin address is returned by the https://api.mobbr.com/api_v1/uris/info API-call that is already done by this page. 

Use a new section in the layout.

**Comment by davidsemakula** [comment]
Checkout https://github.com/mobbr/mobbr-frontend/pull/318 for a fix for this issue

**Comment by jrjackso** [comment]
This doesn't seem like it should be a 5/6, 6/6 thing.. @patricksavalle ?
(Otherwise, looked over the code and I can merge assuming it hit the mark on the requirements)

**Comment by davidsemakula** [comment]
@jrjackso @patricksavalle wasn't too sure about the 5/6 and 6/6 myself.

But I figured you would comment so I can make the required changes if necessary.

**Comment by patricksavalle** [comment]
@davidsemakula @jrjackso  This is not a 3/5, 4/5 thing indeed. But I closed the item anyway, we will fix this ourselves!

It is now on TEST: https://test-www.mobbr.com/#/task/aHR0cHM6Ly9naXRodWIuY29tL21vYmJyL21vYmJyLWZyb250ZW5kL2lzc3Vlcy8yNDg=
