### ISSUE TITLE
Instructions on how to claim money in TASK tile 4

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#289]
Can we fit the claim instructions on the person cards? 

When the card shows <unclaimed> it should show have an alternative content/layout. It should show the claim instructions and the claimable ID. And the amount. No more.

- Go to settings/ids
- Connect the following ID: https://github.com/blabla

Could need some API mods, I will be stand-by.

![screen shot 2015-04-07 at 18 11 21](https://cloud.githubusercontent.com/assets/701331/7027751/98a0606a-dd51-11e4-95b1-562b92e7b721.png)

**Comment by handijk** [comment]
This needs the unclaimed id in the response JSON of persons/uri
