### ISSUE TITLE
HTTPS problems

### ISSUE THREAD

**Issue by Diapolo** [mobbr/mobbr-frontend#295]
Firefox keeps telling me, that my connection to https://mobbr.com is not completely secure, because it contains unencrypted elements. IHMO this should not happen.

**Comment by patricksavalle** [comment]
Now I understand the problem. We noticed this problem on Chrome/Android, but the certificate is valid. The problem is apparently we are embedding non-HTTPS elements in the page. These should be cached/proxied or removed. @handijk ?

**Comment by patricksavalle** [comment]
I cannot reproduce this on Firefox OSX or Firefox Windows 10.

**Comment by patricksavalle** [comment]
Not on Firefox Ubuntu 14 either. 

@Diapolo could you please add a screen shot or something? Which exact URL does this happen?

**Comment by Diapolo** [comment]
Strange, it seems it had something to do with an addon which blocks HTTP referrers in Firefox 38. I changed some settings and now the warning is gone. I guess this was a no-bug, but a problem on my side. Thanks for taking a look!

**Comment by patricksavalle** [comment]
Thank you for helping us, by intention :)
