### ISSUE TITLE
Simplify button embed recipe on /TASK page

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#305]
@handijk  It it possible to combine step 3 and 4?

Like this?

    <script type="text/javascript" src="https://mobbr.com/mobbr-button.js"></script>
    <script type="text/javascript">
        mobbr.button('https://github.com/mobbr/mobbr-browser-plugin', 'EUR', 'medium');
    </script>

Or possible even this?

    <script type="text/javascript" src="https://mobbr.com/mobbr-button.js">
        mobbr.button('https://github.com/mobbr/mobbr-browser-plugin', 'EUR', 'medium');
    </script>

The script itself has a protected against multiple inclusions already.

And while at it: would be nice if on chosing a currency, the buttons refresh to this currency.

![screen shot 2015-05-19 at 17 55 28](https://cloud.githubusercontent.com/assets/701331/7707493/59592732-fe50-11e4-881a-d97fbe4e8fcb.png)

**Comment by davidsemakula** [comment]
@patricksavalle second suggestion is a bad idea

https://developer.mozilla.org/en/docs/Web/HTML/Element/script

> ###### If a script element has a src attribute specified, it should not have a script embedded inside its tags.

**Comment by davidsemakula** [comment]
Check out https://github.com/mobbr/mobbr-frontend/pull/320

**Comment by patricksavalle** [comment]
We will test this on TEST-WWW.MOBBR.COM this week :)
