### ISSUE TITLE
Create exchangerates page /FOREX

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#98]
Just show a table listing all exchangerates as return by API-call https://api.mobbr.com/api_v1/api/currencies

Use URL: /#/forex

Make sure the HTML is clean, next step is to apply CSS/style. Use HTML structure of tables at /PAYMENTS page.

<img width="968" alt="screen shot 2015-07-25 at 14 24 08" src="https://cloud.githubusercontent.com/assets/701331/8889377/f4fcea0e-32d8-11e5-9fc0-61cdfd19061e.png">

Would be nice if the URL can contain the base currency. Like: /#/forex/usd or /#/forex/eur. 

See https://github.com/mobbr/mobbr-frontend for instructions on installing the Mobbr AngularJS app.

**Comment by jrjackso** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2060208/8889558/fdd6d742-32ac-11e5-844a-982aa1c643f6.png)

**Comment by jrjackso** [comment]
@patricksavalle let me know if this is good and if so i'll merge into develop/close the issue

**Comment by patricksavalle** [comment]
@jrjackso looks good :) 

Ideally I would like to have the base-currency and the last-update time (just take the update time associated with the base-currency) in the title, so the base-currency column can be dropped, and the host-part of the exchange_rate_source_url as extra column (source).

**Comment by jrjackso** [comment]
K.. Think this should do it then. You have to pass the base currency on the URL now b/c page just does 1 (i.e. forex/eur)

![untitled](https://cloud.githubusercontent.com/assets/2060208/8891519/5effefec-32fb-11e5-9db9-3ba4d9e920ad.png)

**Comment by jrjackso** [comment]
Also worth noting that the currencies endpoint only returns EUR (base) currently, so anything other than the forex/eur will show a blank table.

**Comment by jrjackso** [comment]
I changed 'host' to 'source' for the column name btw (forgot to tag the checkin with issue # ). IMO source sounds better.

**Comment by patricksavalle** [comment]
:+1:
